#!/usr/bin/env python3
"""Verify the public docs corpus against the code it claims to describe.

Mechanical checks only — no model in the loop. What it enforces:

1. **Allowlist exactness, both directions**, against `git ls-files docs/`: every tracked
   file has a manifest entry, and every manifest entry names a tracked file. One direction
   is not enough — an entry naming an existing-but-untracked file passes locally while the
   pushed commit does not contain it, so the corpus verified is not the corpus published.
2. **Admitted extensions only** (`.md`, `.txt`, `.yaml`), checked across everything tracked
   under `docs/` rather than only manifested entries. A binary cannot be read in review, so
   it has no place in a corpus whose whole claim is auditability.
3. **Manifest schema**: required fields, correct types, table-safe strings, no duplicates,
   no traversal, no symlinks, no whitespace in paths. Malformed YAML is a finding, not a
   traceback.
4. **Anchors resolve and stay inside the published commit**: `file:line` is rejected
   outright, and so are absolute paths, traversal, symlinks, and paths git does not track.
5. **Growth budget**: documents <= 25 KB so one fits in context beside the code it
   describes; generated indexes <= 40 KB. Nothing shards on its own — exceeding it fails.
6. **Structure**: every document carries exactly one ordered SOURCEMAP marker pair, or its
   generated map silently does not exist.
7. **Invariants**: defined once, every reference resolves, `defines_invariants` matches
   what is actually in the file — both directions — and every declared invariant names a
   test that fails when it is false.
8. **The corpus skeleton exists**: a manifest holding only its own meta entry would
   otherwise pass every check above while the navigation surfaces had been deleted.
9. **Prose names real code**: a backticked `module.py`, `Class.method` or `func()` that
   does not exist in the tracked tree is refused. Anchors being right is not enough — the
   prose is what a reader acts on.

`EXCLUDED_TREES` is the one place a tracked file under `docs/` escapes all of this; see
its comment.

Usage:
    python3 -m scripts.verify_docs [repo_root] [--report] [--write-nav] [--check-nav]
"""
from __future__ import annotations

import ast
import re
import subprocess
import sys
from pathlib import Path

import yaml

LINE_ANCHOR = re.compile(r"^[^:]+:\d+$")
INV_DEFINITION = re.compile(r"\*\*(INV-[A-Z]+-\d+)\*\*\s*:")
INV_REFERENCE = re.compile(r"\b(INV-[A-Z]+-\d+)\b")

CEILING_BYTES = 25_000
WARN_BYTES = 20_000
INDEX_CEILING_BYTES = 40_000

DOCUMENT_KINDS = {"document"}
INDEX_KINDS = {"index", "generated", "meta"}
ALL_KINDS = DOCUMENT_KINDS | INDEX_KINDS
ALLOWED_SUFFIXES = {".md", ".txt", ".yaml"}
ALLOWED_TOP_DIRS = {"architecture", "doctrine", "contributing", "reference"}
TABLE_SAFE_FIELDS = ("summary", "when_changing")
LIST_FIELDS = ("covers", "tests", "related", "defines_invariants")

#: Trees tracked under `docs/` that are NOT the corpus. Working material —
#: design documents and implementation plans — lives here; it is untracked
#: before publication, and until then the corpus gate would otherwise demand a
#: manifest entry for every file in it. Excluded in BOTH directions: these
#: files are not demanded by the allowlist, and they may not be manifested,
#: anchored or linked to either, because a reader of the public commit does not
#: have them. The same trees are excluded by declared entry from
#: `scan_identifiers.py` and `scan_lineage.py`.
#:
#: This constant stays after the tree is untracked. Removing it would let a
#: re-added file walk straight into the corpus unmanifested, which is the one
#: failure the allowlist exists to prevent.
EXCLUDED_TREES = ("superpowers/",)

# An invariant bound to this literal has NO pinning test yet. The sentinel exists so the
# backlog is mechanical: the verifier is red until every sentinel is replaced by a real
# test that has been demonstrated to fail when the invariant is false.
PINNING_SENTINEL = "tests/PINNING-TEST-MISSING"

REQUIRED_SKELETON = {
    "README.md",
    "llms.txt",
    "manifest.yaml",
    "coverage.yaml",
    "doctrine/invariants.md",
    "doctrine/publishing.md",
    "contributing/doc-contract.md",
}

ROUTING_BEGIN, ROUTING_END = "<!-- BEGIN ROUTING -->", "<!-- END ROUTING -->"
SOURCEMAP_BEGIN, SOURCEMAP_END = "<!-- BEGIN SOURCEMAP -->", "<!-- END SOURCEMAP -->"
GENERATED_NOTE = "<!-- generated by scripts/verify_docs.py --write-nav; do not hand-edit -->"
CODE_WINS = (
    "> Code is the source of truth. This file is a map; when it and the code disagree, "
    "the code wins."
)

SECTIONS = (
    ("Architecture", "architecture/"),
    ("Reference", "reference/"),
    ("Doctrine", "doctrine/"),
    ("Contributing", "contributing/"),
)


def _excluded(rel: str) -> bool:
    """Is this docs-relative path inside an excluded tree?"""
    return any(rel == tree.rstrip("/") or rel.startswith(tree) for tree in EXCLUDED_TREES)


# --- anchors -------------------------------------------------------------------------

def parse_anchor(anchor: str) -> tuple[str, str | None]:
    """Split `path::Dotted.Symbol` into its parts. A bare path yields no symbol."""
    if "::" in anchor:
        path, symbol = anchor.split("::", 1)
        return path, symbol
    return anchor, None


def symbol_exists(path: Path, dotted: str) -> bool:
    """Resolve a dotted symbol (`Class.method`, `func`) in a Python file."""
    try:
        tree: ast.AST = ast.parse(path.read_text())
    except (OSError, SyntaxError, ValueError):
        return False
    node = tree
    for part in dotted.split("."):
        for child in ast.iter_child_nodes(node):
            if getattr(child, "name", None) == part:
                node = child
                break
        else:
            return False
    return True


def yaml_key_exists(path: Path, dotted: str) -> bool:
    """Resolve a dotted key path in a YAML file."""
    try:
        data = yaml.safe_load(path.read_text())
    except (OSError, yaml.YAMLError):
        return False
    for part in dotted.split("."):
        if not isinstance(data, dict) or part not in data:
            return False
        data = data[part]
    return True


# --- git ground truth ----------------------------------------------------------------

def _git(repo_root: Path, *args: str) -> str:
    return subprocess.run(
        ["git", "-C", str(repo_root), *args],
        capture_output=True, text=True, check=True,
    ).stdout


def tracked_files(repo_root: Path) -> set[str]:
    """Every path git tracks, repo-relative.

    An anchor must name one of these: without the check it could point at ignored or local
    content and pass while being absent from the public commit, which is exactly what the
    publication rule forbids. A dirty-tree check does not notice ignored files.
    """
    return {line for line in _git(repo_root, "ls-files").splitlines() if line.strip()}


def tracked_docs(repo_root: Path) -> set[str]:
    """Every file git tracks under docs/, relative to docs/, minus the excluded trees.

    A glob over `*.md` would miss `docs/dump.json`, an image, or an extensionless file —
    all of which would be published without ever appearing in the manifest.
    """
    prefix = "docs/"
    return {
        line[len(prefix):]
        for line in _git(repo_root, "ls-files", prefix).splitlines()
        if line.strip() and not _excluded(line[len(prefix):])
    }


# --- manifest ------------------------------------------------------------------------

class _DuplicateKeyLoader(yaml.SafeLoader):
    """PyYAML silently keeps the LAST of a duplicate key, so a manifest entry can carry two
    `covers` blocks and quietly publish only one. Reject them instead."""


def _no_duplicate_keys(loader, node, deep=False):
    seen, dupes = set(), []
    for key_node, _ in node.value:
        key = loader.construct_object(key_node, deep=True)
        if key in seen:
            dupes.append(key)
        seen.add(key)
    if dupes:
        raise yaml.YAMLError(f"duplicate key(s) in a manifest entry: {sorted(dupes)}")
    return yaml.SafeLoader.construct_mapping(loader, node, deep)


_DuplicateKeyLoader.construct_mapping = _no_duplicate_keys


def _manifest_files(docs_dir: Path) -> list[Path]:
    """The root manifest plus every shard, in a deterministic order.

    `manifest.yaml` is required and stays the entry point; when it reaches the
    index ceiling, entries move to `manifest.d/<name>.yaml` shards. Each shard
    is a plain top-level list, exactly like the root, and each shard FILE must
    itself carry a manifest entry (publication is allowlist-only)."""
    return [docs_dir / "manifest.yaml"] + sorted((docs_dir / "manifest.d").glob("*.yaml"))


def _load_entries(docs_dir: Path) -> tuple[list[dict], list[str]]:
    """Parse the manifest (root + `manifest.d/` shards), normalising anything a
    later caller would trip over.

    Normalisation happens HERE rather than per-entry because `verify()` builds sets from
    these values before per-entry validation runs, and `kind: []` is unhashable.
    """
    raw: list = []
    problems: list[str] = []
    for source in _manifest_files(docs_dir):
        label = f"docs/{source.relative_to(docs_dir)}"
        try:
            part = yaml.load(source.read_text(), _DuplicateKeyLoader)
        except yaml.YAMLError as exc:
            return [], [f"{label} is not valid YAML: {exc}"]
        except OSError as exc:
            return [], [f"{label} is unreadable: {exc}"]
        if not isinstance(part, list):
            return [], [f"{label} must be a list of entries"]
        raw.extend(part)

    entries: list[dict] = []
    for index, entry in enumerate(raw):
        if not isinstance(entry, dict) or not isinstance(entry.get("doc"), str):
            problems.append(f"manifest entry {index} is not a mapping with a string `doc` key")
            continue
        if "kind" in entry and not isinstance(entry["kind"], str):
            problems.append(f"{entry['doc']}: `kind` must be a string")
            entry["kind"] = "document"
        for field in LIST_FIELDS:
            value = entry.get(field)
            if value is not None and (
                not isinstance(value, list)
                or not all(isinstance(item, str) for item in value)
            ):
                problems.append(f"{entry['doc']}: `{field}` must be a list of strings")
                entry[field] = []
        bindings = entry.get("invariant_tests")
        if bindings is not None and not (
            isinstance(bindings, dict)
            and all(
                isinstance(inv, str)
                and isinstance(tests, list)
                and all(isinstance(t, str) for t in tests)
                for inv, tests in bindings.items()
            )
        ):
            problems.append(
                f"{entry['doc']}: `invariant_tests` must be a mapping of invariant id to "
                f"a list of test references"
            )
            entry["invariant_tests"] = {}
        entries.append(entry)
    return entries, problems


def _check_entry_shape(entry: dict, seen: set[str]) -> list[str]:
    doc = entry["doc"]
    problems: list[str] = []

    if doc in seen:
        problems.append(f"manifest: {doc!r} is listed twice")
    seen.add(doc)

    if doc != doc.strip() or any(ch.isspace() for ch in doc):
        problems.append(
            f"{doc!r}: manifest paths must not contain whitespace — they pass through "
            f"shell pipelines in CI"
        )

    kind = entry.get("kind", "document")
    if kind not in ALL_KINDS:
        problems.append(f"{doc}: unknown kind {kind!r}")
        entry["kind"] = "document"
        kind = "document"

    required = ("summary", "when_changing") if kind in DOCUMENT_KINDS else ("summary",)
    for field in required:
        value = entry.get(field)
        if value is None or (isinstance(value, str) and not value.strip()):
            problems.append(f"{doc}: `{field}` is required")
    for field in TABLE_SAFE_FIELDS:
        value = entry.get(field)
        if value is None:
            continue
        if not isinstance(value, str):
            problems.append(f"{doc}: `{field}` must be a string")
        elif "|" in value or "\n" in value:
            problems.append(
                f"{doc}: `{field}` must be single-line and free of `|` — it is rendered "
                f"into a Markdown table"
            )
    return problems


def _contained(root: Path, rel: str) -> Path | None:
    """Resolve `rel` under `root`, or None if it escapes. Absolute paths always escape."""
    candidate = Path(rel)
    if candidate.is_absolute() or ".." in candidate.parts:
        return None
    target = root / candidate
    try:
        target.resolve(strict=False).relative_to(root.resolve(strict=False))
    except ValueError:
        return None
    return target


def _resolve_doc(docs_dir: Path, doc: str) -> tuple[Path | None, list[str]]:
    """Reject anything that is not a plain relative path to a permitted regular file."""
    target = docs_dir / doc
    # Symlinks first: a symlink to /etc/passwd "exists" and resolves outside docs/, and the
    # clearer error is that the corpus holds regular files only.
    if target.is_symlink():
        return None, [f"{doc}: is a symlink; the corpus contains regular files only"]
    if _contained(docs_dir, doc) is None:
        return None, [f"{doc}: manifest paths must stay inside docs/ — this points outside"]
    if target.suffix not in ALLOWED_SUFFIXES:
        return None, [
            f"{doc}: extension {target.suffix or '(none)'} is not admitted — the corpus "
            f"holds {', '.join(sorted(ALLOWED_SUFFIXES))} only, because nothing else can "
            f"be swept or read in review"
        ]
    if not target.exists():
        return None, [f"manifest names {doc!r} but the file does not exist"]
    if not target.is_file():
        return None, [f"{doc}: is not a regular file"]
    return target, []


def _check_anchor(repo_root: Path, anchor: str, doc: str, tracked: set[str]) -> list[str]:
    if LINE_ANCHOR.match(anchor):
        return [f"{doc}: line-number anchor {anchor!r} — use path::Symbol instead"]
    rel, symbol = parse_anchor(anchor)
    target = _contained(repo_root, rel)
    if target is None:
        return [
            f"{doc}: anchor {anchor!r} points outside the repository — a doc may only "
            f"anchor to what the public commit contains"
        ]
    if rel.startswith("docs/") and _excluded(rel[len("docs/"):]):
        return [
            f"{doc}: anchor {anchor!r} points into excluded working material — it is "
            f"tracked today and is not published, so a reader cannot open it"
        ]
    if rel not in tracked:
        return [
            f"{doc}: anchor {anchor!r} is not tracked by git — a doc may only anchor to "
            f"what the public commit contains, not to ignored or local files"
        ]
    # A TRACKED symlink whose destination is untracked would otherwise pass: the lexical
    # path is in the tree, and symbol resolution then reads the destination's contents.
    if target.is_symlink():
        return [
            f"{doc}: anchor {anchor!r} is a symlink — it resolves to content that may not "
            f"be in the public commit; anchor the real path"
        ]
    if target.exists() and not target.is_file():
        return [f"{doc}: anchor {anchor!r} is not a regular file"]
    if not target.exists():
        return [f"{doc}: anchor {anchor!r} names a file that does not exist"]
    if symbol is None:
        return []
    if target.suffix == ".py":
        ok = symbol_exists(target, symbol)
    elif target.suffix in (".yaml", ".yml"):
        ok = yaml_key_exists(target, symbol)
    else:
        return [f"{doc}: anchor {anchor!r} — symbols resolve only in .py/.yaml"]
    return [] if ok else [f"{doc}: anchor {anchor!r} does not resolve"]


# Tokens that look like code but are prose or well-known non-source names. Anything added
# here is a deliberate exemption and should be rare: when this check fires, the document is
# usually wrong, and the fix is the sentence rather than another token. The list holds only
# shapes this tree actually contains — an exemption for something absent is dead weight
# that hides the next real one.
PROSE_TOKENS = {
    "CLAUDE.md", "AGENTS.md", "README.md", "SKILL.md", "LICENSE.md",
    "manifest.yaml", "manifest.json", "plugin.json", "config-schema.json",
    "role.yaml", "doctrine.md", "persona.md", "persona.yaml", "coverage.yaml",
    "llms.txt", "requirements-dev.txt",
}
# `foo.py`, `Thing.method`, `func()` — the shapes that assert a code identifier exists.
PROSE_CODE = re.compile(
    r"`("
    r"[a-z_][a-z0-9_]*\.py"                     # a module
    r"|[A-Z][A-Za-z0-9_]*\.[a-z_][a-z0-9_]*"    # Class.method
    r"|_?[a-z][a-z0-9_]{3,}\(\)"               # func()
    r")`"
)


def _code_identifiers(text: str) -> set[str]:
    return {m.group(1) for m in PROSE_CODE.finditer(text)} - PROSE_TOKENS


def _without_nested_classes(scope: ast.AST):
    """Walk a scope, never descending into a nested class definition."""
    stack = list(ast.iter_child_nodes(scope))
    while stack:
        node = stack.pop()
        if isinstance(node, ast.ClassDef):
            continue
        yield node
        stack.extend(ast.iter_child_nodes(node))


def _self_attributes(target: ast.AST) -> set[str]:
    """`self.x` names bound by this assignment target, unpacking tuples and lists
    so `self.value, other = …` is not mistaken for no assignment at all."""
    if isinstance(target, (ast.Tuple, ast.List)):
        found: set[str] = set()
        for element in target.elts:
            found |= _self_attributes(element)
        return found
    if isinstance(target, ast.Starred):
        return _self_attributes(target.value)
    if (
        isinstance(target, ast.Attribute)
        and isinstance(target.value, ast.Name)
        and target.value.id == "self"
    ):
        return {target.attr}
    return set()


def _defined_symbols(
    repo_root: Path, tracked: set[str]
) -> tuple[set[str], set[str], set[str]]:
    """Module basenames, every def/class name, and the classes whose bases are unknown.

    The third set is what makes `Class.member` decidable in three states rather than two.
    A class whose every base resolves inside this tree has a KNOWN membership: anything
    not in it is a false claim. A class inheriting from something outside the tree —
    `Exception`, a library type — has an unknowable membership, and refusing a member of
    it would flag honest prose. Only the middle case can be judged, and only it is.
    """
    modules: set[str] = set()
    names: set[str] = set()
    #: Keyed by `<module stem>.<class>`, so two classes with one name stay two
    #: classes. The bare name is only a fallback for prose, which does not
    #: qualify.
    members: dict[str, set[str]] = {}
    bases: dict[str, list[str]] = {}
    def module_path(rel: str) -> str:
        """`pkg/base.py` -> `pkg.base`. Two modules of one stem in different
        directories are two modules; keying by stem pooled their classes, and a
        namesake's members were credited to a class that never inherited them."""
        return rel[:-3].replace("/", ".")

    module_paths = {
        module_path(rel) for rel in tracked if rel.endswith(".py")
    }

    for rel in sorted(tracked):
        if not rel.endswith(".py"):
            continue
        modules.add(Path(rel).name)
        here = module_path(rel)
        try:
            tree = ast.parse((repo_root / rel).read_text())
        except (OSError, SyntaxError, ValueError):
            continue
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                names.add(node.name)

        # What this file IMPORTS, and where from. A base that is imported is NOT the
        # same-named class defined elsewhere in the tree — merging them by bare name
        # credited a class with an unrelated namesake's members. But when the import
        # names a module this tree tracks, the base IS decidable, and calling it
        # unknown hides a false claim instead. So resolve what resolves, and open
        # the class only for a base that genuinely leaves the tree.
        package = here.rsplit(".", 1)[0] if "." in here else ""

        def resolve_relative(level: int, dotted: str) -> str | None:
            """`from .base import Base` resolves EXACTLY within this module's
            package — Python leaves no ambiguity there, so falling back to a
            suffix match across the tree (and finding two candidates, and giving
            up) declared the class unknowable when it was decidable."""
            parts = package.split(".") if package else []
            if level > 1:
                parts = parts[:-(level - 1)] if len(parts) >= level - 1 else None
            if parts is None:
                return None
            target = ".".join([*parts, dotted] if dotted else parts)
            return target if target in module_paths else None

        def resolve_module(dotted: str) -> str | None:
            """A module reference as written -- absolute, package-qualified or a
            bare name -- against the modules this tree tracks. A suffix match
            covers `pkg.base` written from inside `pkg/`, and is only accepted
            when exactly one tracked module matches: two candidates mean the
            reference is ambiguous, and guessing would be the pooling bug again."""
            if dotted in module_paths:
                return dotted
            matches = [m for m in module_paths
                       if m == dotted or m.endswith("." + dotted)]
            return matches[0] if len(matches) == 1 else None

        imported: dict[str, str | None] = {}
        module_alias: dict[str, str] = {}
        for node in ast.walk(tree):
            if isinstance(node, ast.ImportFrom):
                source = (
                    resolve_relative(node.level, node.module or "")
                    if node.level else resolve_module(node.module or "")
                )
                for alias in node.names:
                    local = alias.asname or alias.name
                    imported[local] = f"{source}.{alias.name}" if source else None
            elif isinstance(node, ast.Import):
                for alias in node.names:
                    local = alias.asname or alias.name.split(".")[0]
                    target = resolve_module(alias.name)
                    if target and alias.asname:
                        module_alias[local] = target
                    elif target and "." not in alias.name:
                        module_alias[local] = target
                    imported[local] = None

        # Every class anywhere, not only top-level ones: a method of a nested class
        # is still a method, and treating it as unqualified would flag honest prose.
        for node in ast.walk(tree):
            if not isinstance(node, ast.ClassDef):
                continue
            qualified = f"{here}.{node.name}"
            own = members.setdefault(qualified, set())
            resolved = []
            for base in node.bases:
                if isinstance(base, ast.Name):
                    if base.id in imported:
                        resolved.append(imported[base.id] or "?")
                    else:
                        resolved.append(f"{here}.{base.id}")
                elif isinstance(base, ast.Attribute):
                    # `import pkg.base` then `class Store(pkg.base.Base)` -- a
                    # perfectly ordinary shape that used to open the class.
                    parts, cursor = [], base
                    while isinstance(cursor, ast.Attribute):
                        parts.append(cursor.attr)
                        cursor = cursor.value
                    if isinstance(cursor, ast.Name):
                        parts.append(cursor.id)
                        parts.reverse()
                        owner = module_alias.get(parts[0]) or resolve_module(
                            ".".join(parts[:-1]))
                        resolved.append(f"{owner}.{parts[-1]}" if owner else "?")
                    else:
                        resolved.append("?")
                else:
                    resolved.append("?")
            bases.setdefault(qualified, []).extend(resolved)

            for sub in node.body:
                if isinstance(sub, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    own.add(sub.name)
                    # `self.value = …` in a method of THIS class is as real a member
                    # as a class-level one, and most attributes a document names are
                    # bound that way. Not a nested class's `self`: that is the inner
                    # class's attribute, and crediting it outward accepts a false
                    # claim.
                    for inner in _without_nested_classes(sub):
                        targets = []
                        if isinstance(inner, ast.Assign):
                            targets = list(inner.targets)
                        elif isinstance(inner, (ast.AnnAssign, ast.AugAssign)):
                            targets = [inner.target]
                        for target in targets:
                            own |= _self_attributes(target)
                # Class-level attributes are as citable as methods, and a dataclass
                # field is a bare annotation. Collecting only callables would flag
                # attributes that plainly exist.
                elif isinstance(sub, ast.AnnAssign) and isinstance(sub.target, ast.Name):
                    own.add(sub.target.id)
                elif isinstance(sub, ast.Assign):
                    for target in sub.targets:
                        if isinstance(target, ast.Name):
                            own.add(target.id)

    # A qualified class cannot be judged if any base, at any depth, is not defined in
    # this tree.
    open_qualified: set[str] = set()
    for cls in members:
        seen, stack = set(), list(bases.get(cls, []))
        while stack:
            base = stack.pop()
            if base in seen:
                continue
            seen.add(base)
            if base not in members:
                open_qualified.add(cls)
                break
            stack.extend(bases.get(base, []))

    # Inheritance expansion, then collapse to the bare names prose actually uses. A
    # bare name is open if ANY class of that name is: prose cannot say which one it
    # meant, and refusing an honest sentence is the worse error.
    open_classes: set[str] = set()
    for cls, own in members.items():
        bare = cls.rsplit(".", 1)[1]
        inherited = set(own)
        seen, stack = set(), list(bases.get(cls, []))
        while stack:
            base = stack.pop()
            if base in seen or base not in members:
                continue
            seen.add(base)
            inherited |= members[base]
            stack.extend(bases.get(base, []))
        names |= {f"{bare}.{member}" for member in inherited}
        if cls in open_qualified:
            open_classes.add(bare)
    return modules, names, open_classes


def _check_prose_code(text: str, doc: str, modules: set[str], names: set[str],
                      open_classes: set[str] | None = None) -> list[str]:
    """A document must not name code that does not exist.

    Anchors are checked above; the PROSE is what a reader acts on, and a sentence naming a
    deleted method survives anchor verification untouched because the anchors are right and
    only the sentence is wrong.
    """
    open_classes = open_classes or set()
    problems = []
    for token in sorted(_code_identifiers(text)):
        if token.endswith(".py"):
            ok = token in modules
        elif token.endswith("()"):
            bare = token[:-2]
            ok = bare in names or any(n.endswith(f".{bare}") for n in names)
        else:
            # `Class.member`, judged in three states. An exact hit — including a member
            # inherited from a base inside this tree — passes. A class whose bases leave
            # the tree cannot be judged and passes. Everything else is refused: a member
            # of some OTHER class is not a member of this one, and accepting it because
            # the bare name exists somewhere is exactly the false ownership claim this
            # check advertises catching.
            cls, bare = token.split(".", 1)
            known_class = cls in names or any(n.startswith(f"{cls}.") for n in names)
            if token in names or cls in open_classes:
                ok = True
            elif known_class:
                problems.append(
                    f"{doc}: names `{token}` in prose, but `{bare}` is not a member of "
                    f"`{cls}` — it belongs to another class, is a plain function, or is a "
                    f"nested closure. Name where it actually lives."
                )
                continue
            else:
                ok = False
        if not ok:
            problems.append(
                f"{doc}: names `{token}` in prose, which does not exist in the tracked code"
            )
    return problems


#: Every Markdown destination shape CommonMark admits, because a check that understands
#: one spelling and not its sibling is not a check. Inline `](dest)`, inline with the
#: angle-bracket form `](<dest>)`, and the reference definition `[label]: dest` — the last
#: one is where a link's destination usually lives when a document has many.
MARKDOWN_INLINE_LINK = re.compile(r"\]\(\s*<([^>]*)>|\]\(\s*([^)\s]+)")
#: A reference label may contain an ESCAPED bracket (`[plan\]]`), so the label is
#: matched as "anything but an unescaped `]`" rather than "anything but `]`".
MARKDOWN_REFERENCE_DEF = re.compile(
    r"(?m)^[ ]{0,3}\[(?:[^\]\\]|\\.)+\]:\s*<?([^>\s]+)>?"
)


#: Markdown admits raw HTML, so `<a href="…">` is a link a reader clicks exactly like
#: the bracket forms. Also `src`, for an embed.
HTML_LINK = re.compile(
    r"""(?i)<[a-z][^>]*?\s(?:href|src)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'=<>`]+))"""
)


def _link_targets(text: str) -> list[str]:
    targets = [
        angled or plain for angled, plain in MARKDOWN_INLINE_LINK.findall(text)
    ]
    targets += MARKDOWN_REFERENCE_DEF.findall(text)
    targets += [
        quoted or single or bare for quoted, single, bare in HTML_LINK.findall(text)
    ]
    return [t for t in targets if t]


def _check_links(text: str, doc: str) -> list[str]:
    """A document may not LINK into an excluded tree.

    The anchor check covers `covers:`/`tests:`; a Markdown link in the prose is the same
    promise made in the form a reader actually clicks, and it was the one that could not
    fire. External links (a scheme, or a bare fragment) are not this check's business.
    """
    problems = []
    here = Path(doc).parent
    for target in _link_targets(text):
        if "://" in target or target.startswith(("#", "mailto:")):
            continue
        rel = (here / target.split("#", 1)[0]).as_posix()
        # Normalise `../` without touching the filesystem: the target need not exist for
        # the rule to apply.
        parts: list[str] = []
        for part in rel.split("/"):
            if part in ("", "."):
                continue
            if part == ".." and parts and parts[-1] != "..":
                parts.pop()
            else:
                parts.append(part)
        if _excluded("/".join(parts)):
            problems.append(
                f"{doc}: links to {target!r}, which is inside excluded working material "
                f"— it is not published, so the link is dead for every reader"
            )
    return problems


def _check_invariant_tests(entry: dict, repo_root: Path, tracked: set[str]) -> list[str]:
    """Every invariant must name a test that fails if the invariant is false.

    Without this an invariant is an assertion, not a contract: the corpus stays green
    while the property it states quietly stops being true. The binding is checked both
    ways — a declared invariant with no test is refused, and so is a binding for an
    invariant the entry no longer declares, which would keep a dead test looking
    load-bearing.
    """
    doc = entry["doc"]
    declared = entry.get("defines_invariants") or []
    bindings = entry.get("invariant_tests") or {}
    problems: list[str] = []
    for inv in declared:
        refs = bindings.get(inv) or []
        if not refs:
            problems.append(
                f"{doc}: {inv} has no pinning test — bind one in `invariant_tests`, or "
                f"the sentinel {PINNING_SENTINEL} to record the debt visibly"
            )
            continue
        for ref in refs:
            if ref == PINNING_SENTINEL:
                problems.append(
                    f"{doc}: {inv} is bound to {PINNING_SENTINEL} — the invariant has no "
                    f"pinning test yet; write one and demonstrate its red case"
                )
                continue
            rel, node = parse_anchor(ref)
            if rel not in tracked:
                problems.append(
                    f"{doc}: {inv} names {ref!r} but git does not track {rel!r} — a "
                    f"pinning test must be in the published commit"
                )
                continue
            if node is None:
                continue
            if "::" in node:
                # A class-qualified node id (`Class::method`) — a runnable anchor. Python
                # source never contains a literal "::" between a class and its method, so
                # the plain substring search below can never match this shape; verify it
                # structurally instead, exactly as a `covers:` symbol is verified.
                if not symbol_exists(repo_root / rel, node.replace("::", ".")):
                    problems.append(
                        f"{doc}: {inv} names {ref!r} but {node!r} does not "
                        f"resolve in {rel}"
                    )
                continue
            # A plain string search, not test collection: cheap, dependency-free, and
            # enough to catch a renamed or deleted test function.
            try:
                text = (repo_root / rel).read_text(errors="replace")
            except OSError:
                text = ""
            if node not in text:
                problems.append(
                    f"{doc}: {inv} names {ref!r} but {node!r} does not appear in {rel}"
                )
    for inv in sorted(set(bindings) - set(declared)):
        problems.append(
            f"{doc}: invariant_tests binds {inv}, which the entry does not declare in "
            f"defines_invariants"
        )
    return problems


def _check_sourcemap(target: Path, doc: str) -> list[str]:
    """A document without exactly one ordered marker pair gets no generated map at all."""
    text = target.read_text(errors="replace")
    begins, ends = text.count(SOURCEMAP_BEGIN), text.count(SOURCEMAP_END)
    if begins != 1 or ends != 1:
        return [
            f"{doc}: must contain exactly one SOURCEMAP marker pair (found {begins} begin, "
            f"{ends} end) — otherwise its Source & test map is never generated"
        ]
    if text.index(SOURCEMAP_BEGIN) > text.index(SOURCEMAP_END):
        return [f"{doc}: SOURCEMAP markers are reversed"]
    return []


def _budget_for(kind: str) -> int:
    return CEILING_BYTES if kind in DOCUMENT_KINDS else INDEX_CEILING_BYTES


def _check_invariants(docs_dir: Path, entries: list[dict]) -> list[str]:
    defined: dict[str, list[str]] = {}
    statements: dict[str, str] = {}
    referenced: dict[str, str] = {}
    per_doc: dict[str, set[str]] = {}

    for entry in entries:
        doc = entry["doc"]
        target = docs_dir / doc
        if target.is_symlink() or not target.is_file():
            continue
        text = target.read_text(errors="replace")
        per_doc[doc] = set()
        for line in text.splitlines():
            match = INV_DEFINITION.search(line)
            if match:
                inv = match.group(1)
                defined.setdefault(inv, []).append(doc)
                statements[inv] = line.split(":", 1)[1].strip()
                per_doc[doc].add(inv)
        for inv in INV_REFERENCE.findall(text):
            referenced.setdefault(inv, doc)

    problems: list[str] = []
    for inv, homes in sorted(defined.items()):
        if len(homes) > 1:
            problems.append(
                f"{inv} is defined {len(homes)} times ({', '.join(sorted(homes))}) — an "
                f"invariant has exactly one defining file"
            )
        statement = statements.get(inv, "")
        if not statement:
            problems.append(f"{inv}: has no statement on its definition line")
        if "|" in statement:
            problems.append(f"{inv}: the statement must be free of `|` — it renders into a table")
        # A wrapped statement renders TRUNCATED into the generated table, because only the
        # definition line is captured. Terminal punctuation is a HEURISTIC for that, not a
        # proof: a complete first sentence followed by an essential qualification on the next
        # line still passes here, and only a human read catches it.
        if statement and statement[-1] not in ".!?":
            problems.append(
                f"{inv}: the statement must be complete on ONE line (it ends with "
                f"{statement[-12:]!r}). A wrapped statement is truncated in the generated "
                f"invariant index."
            )
    for inv, where in sorted(referenced.items()):
        if inv not in defined:
            problems.append(f"{where}: {inv} is referenced but never defined")

    for entry in entries:
        doc = entry["doc"]
        declared = set(entry.get("defines_invariants") or [])
        actual = per_doc.get(doc, set())
        for inv in sorted(declared - actual):
            problems.append(f"{doc}: manifest declares {inv} but the file does not define it")
        for inv in sorted(actual - declared):
            problems.append(f"{doc}: defines {inv} but the manifest does not declare it")
    return problems


# --- the verifier --------------------------------------------------------------------

def verify(repo_root: Path) -> list[str]:
    """Return every problem found in the corpus. Empty list means clean."""
    docs_dir = repo_root / "docs"
    if not (docs_dir / "manifest.yaml").exists():
        return ["docs/manifest.yaml is missing — the corpus is allowlist-only"]

    entries, problems = _load_entries(docs_dir)
    if problems and not entries:
        return problems

    manifested = {entry["doc"] for entry in entries}
    tracked = tracked_files(repo_root)
    modules, names, open_classes = _defined_symbols(repo_root, tracked)
    # `related` must name a real DOCUMENT: the manifest, the README and the generated
    # indexes are all manifested but are not things to go read next.
    related_targets = {
        entry["doc"] for entry in entries
        if entry.get("kind", "document") in DOCUMENT_KINDS
    }

    seen: set[str] = set()
    for entry in entries:
        doc = entry["doc"]
        problems.extend(_check_entry_shape(entry, seen))
        kind = entry.get("kind", "document")

        if _excluded(doc):
            problems.append(
                f"{doc}: is excluded working material and must not be manifested — it is "
                f"not published, so nothing in the corpus may depend on it"
            )
            continue

        parts = Path(doc).parts
        top = parts[0] if len(parts) > 1 else ""
        if top == "manifest.d":
            # Manifest shards only. A document hidden here would escape the routing table
            # and the generated index.
            if kind in DOCUMENT_KINDS:
                problems.append(
                    f"{doc}: manifest.d/ holds manifest shards only — a document "
                    f"must live under one of {', '.join(sorted(ALLOWED_TOP_DIRS))}/"
                )
        elif top and top not in ALLOWED_TOP_DIRS:
            problems.append(
                f"{doc}: {top}/ is not an admitted corpus directory "
                f"({', '.join(sorted(ALLOWED_TOP_DIRS))})"
            )
        # A root-level `document` verifies cleanly but render_llms only emits the configured
        # prefixes, so it would be absent from the flat index it claims to be in.
        if not top and kind in DOCUMENT_KINDS:
            problems.append(
                f"{doc}: a document must live under one of "
                f"{', '.join(sorted(ALLOWED_TOP_DIRS))}/ — a root-level document is omitted "
                f"from the generated index"
            )

        target, path_problems = _resolve_doc(docs_dir, doc)
        problems.extend(path_problems)
        if target is None:
            continue

        size = target.stat().st_size
        budget = _budget_for(kind)
        if size > budget:
            label = "25 KB ceiling" if budget == CEILING_BYTES else "40 KB index ceiling"
            problems.append(
                f"{doc} is {size / 1000:.1f} KB — exceeds the {label}. Split it and "
                f"manifest both halves; the ceiling is not raised, and nothing shards "
                f"on its own."
            )

        if kind in DOCUMENT_KINDS:
            body = target.read_text(errors="replace")
            problems.extend(_check_sourcemap(target, doc))
            problems.extend(
                _check_prose_code(body, doc, modules, names, open_classes)
            )
            problems.extend(_check_links(body, doc))
            # An invariant is a claim about what the code maintains, so the document must
            # name where it is maintained. This cannot prove the anchor is the RIGHT one,
            # but an invariant with nothing to check it against is an assertion, not a
            # contract.
            if (entry.get("defines_invariants") or []) and not (entry.get("covers") or []):
                problems.append(
                    f"{doc}: declares invariants but anchors no source — name the code that "
                    f"maintains them in `covers`"
                )
            problems.extend(_check_invariant_tests(entry, repo_root, tracked))

        for anchor in list(entry.get("covers") or []) + list(entry.get("tests") or []):
            problems.extend(_check_anchor(repo_root, anchor, doc, tracked))
        for rel in entry.get("related") or []:
            if _contained(docs_dir, rel) is None or (docs_dir / rel).is_symlink():
                problems.append(f"{doc}: related {rel!r} must be a plain path inside docs/")
            elif rel not in related_targets:
                problems.append(
                    f"{doc}: related {rel!r} is not a manifested document (indexes, the "
                    f"README and the manifest are not related targets)"
                )

    tracked_under_docs = tracked_docs(repo_root)
    # Extensions are checked across EVERYTHING tracked, not only manifested entries: an
    # unmanifested `.png` would otherwise report only "not in the manifest", and the rule
    # would never fire on the files most likely to violate it.
    for rel in sorted(tracked_under_docs):
        if Path(rel).suffix not in ALLOWED_SUFFIXES:
            problems.append(
                f"docs/{rel}: extension {Path(rel).suffix or '(none)'} is not admitted"
            )
    for extra in sorted(tracked_under_docs - manifested):
        problems.append(
            f"docs/{extra} is tracked but not in the manifest — publication is allowlist-only"
        )
    for phantom in sorted(manifested - tracked_under_docs):
        if _excluded(phantom):
            continue          # already reported above, with the reason that fits
        problems.append(
            f"{phantom} is in the manifest but git does not track it — the pushed commit "
            f"will not contain it, so the corpus verified is not the corpus published"
        )

    for missing in sorted(REQUIRED_SKELETON - manifested):
        problems.append(f"{missing} is required by the corpus contract but is not manifested")
    if not any(entry.get("kind", "document") in DOCUMENT_KINDS for entry in entries):
        problems.append("the corpus contains no documents — only indexes and metadata")

    problems.extend(_check_invariants(docs_dir, entries))
    return problems


def warnings(repo_root: Path) -> list[str]:
    """Non-fatal growth pressure, printed by CI so it is visible before it fails."""
    docs_dir = repo_root / "docs"
    if not (docs_dir / "manifest.yaml").exists():
        return []
    entries, _ = _load_entries(docs_dir)
    out = []
    for entry in entries:
        if entry.get("kind", "document") not in DOCUMENT_KINDS:
            continue
        target = docs_dir / entry["doc"]
        if target.is_symlink() or not target.is_file():
            continue
        size = target.stat().st_size
        if WARN_BYTES <= size <= CEILING_BYTES:
            out.append(
                f"{entry['doc']} is {size / 1000:.1f} KB — approaching the ceiling; plan "
                f"the split before it fails"
            )
    return out


# --- generated navigation ------------------------------------------------------------

def _documents(repo_root: Path) -> list[dict]:
    entries, _ = _load_entries(repo_root / "docs")
    return [e for e in entries if e.get("kind", "document") in DOCUMENT_KINDS]


def render_llms(repo_root: Path) -> str:
    """llms.txt. Links are relative to docs/, since that is where this file lives."""
    lines = [
        "# casa-specialist-finance — the casa household finance specialist",
        "",
        "Canonical current-state documentation for anyone, human or agent, working on this",
        "repository. Code is the source of truth; these files are a map.",
        "",
    ]
    documents = _documents(repo_root)
    for title, prefix in SECTIONS:
        chosen = sorted(
            (e for e in documents if e["doc"].startswith(prefix)), key=lambda e: e["doc"]
        )
        if not chosen:
            continue
        lines += [f"## {title}", ""]
        for entry in chosen:
            lines.append(f"- [{entry['doc']}]({entry['doc']}): {entry['summary'].strip()}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_routing(repo_root: Path) -> str:
    """The README routing table, keyed on the task the reader is about to do.

    Phrased that way because a reader knows what they are about to change before they know
    which subsystem owns it; the table has to meet them there.
    """
    rows = [GENERATED_NOTE, "", "| When you are changing… | Read |", "|---|---|"]
    for entry in sorted(_documents(repo_root), key=lambda e: e.get("when_changing", "")):
        rows.append(
            f"| {entry['when_changing'].strip()} | [`{entry['doc']}`]({entry['doc']}) |"
        )
    return "\n".join(rows) + "\n"


def render_invariants(repo_root: Path) -> str:
    """One row per INV-* id: the statement and the file that defines it."""
    docs_dir = repo_root / "docs"
    found: list[tuple[str, str, str]] = []
    for entry in _documents(repo_root):
        target = docs_dir / entry["doc"]
        if target.is_symlink() or not target.is_file():
            continue
        for line in target.read_text(errors="replace").splitlines():
            match = INV_DEFINITION.search(line)
            if match:
                found.append((match.group(1), line.split(":", 1)[1].strip(), entry["doc"]))
    rows = [
        "# Invariants",
        "",
        GENERATED_NOTE,
        "",
        CODE_WINS,
        "",
        "Every invariant is defined in exactly one file and referenced by id elsewhere.",
        "",
        "| Id | Statement | Defined in |",
        "|---|---|---|",
    ]
    for inv, statement, home in sorted(found):
        rows.append(f"| `{inv}` | {statement} | [`{home}`](../{home}) |")
    return "\n".join(rows) + "\n"


def render_sourcemap(entry: dict) -> str:
    """The per-file Source & test map — generated, so no prose anchor drifts unverified."""
    # Links are relative to the DOCUMENT's own directory, not hardcoded one level up: a
    # future shard at architecture/ledger/foo.md would otherwise emit broken links.
    depth = len(Path(entry["doc"]).parent.parts)
    up = "../" * depth if depth else ""
    lines = [GENERATED_NOTE, ""]
    for label, key in (("Source", "covers"), ("Tests", "tests")):
        anchors = entry.get(key) or []
        if anchors:
            lines.append(f"**{label}**")
            lines += [f"- `{anchor}`" for anchor in anchors]
            lines.append("")
    related = entry.get("related") or []
    if related:
        lines.append("**Related**")
        lines += [f"- [`{rel}`]({up}{rel})" for rel in related]
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _splice(text: str, begin: str, end: str, body: str, where: str) -> str:
    if text.count(begin) != 1 or text.count(end) != 1:
        raise SystemExit(f"{where}: needs exactly one {begin} / {end} pair")
    if text.index(begin) > text.index(end):
        raise SystemExit(f"{where}: {begin} / {end} markers are reversed")
    head, rest = text.split(begin, 1)
    _, tail = rest.split(end, 1)
    return f"{head}{begin}\n{body}{end}{tail}"


def nav_targets(repo_root: Path) -> dict[str, str]:
    """Relative path -> expected full content, for every generated artifact."""
    docs_dir = repo_root / "docs"
    targets = {
        "llms.txt": render_llms(repo_root),
        "doctrine/invariants.md": render_invariants(repo_root),
    }
    readme = docs_dir / "README.md"
    if readme.is_file():
        targets["README.md"] = _splice(
            readme.read_text(), ROUTING_BEGIN, ROUTING_END,
            render_routing(repo_root), "docs/README.md",
        )
    for entry in _documents(repo_root):
        target = docs_dir / entry["doc"]
        if target.is_symlink() or not target.is_file():
            continue
        text = target.read_text()
        if SOURCEMAP_BEGIN in text:
            targets[entry["doc"]] = _splice(
                text, SOURCEMAP_BEGIN, SOURCEMAP_END,
                render_sourcemap(entry), f"docs/{entry['doc']}",
            )
    return targets


def stale_nav(repo_root: Path) -> list[str]:
    """Which generated artifacts are out of date. Pure — writes nothing."""
    docs_dir = repo_root / "docs"
    stale = []
    for rel, expected in nav_targets(repo_root).items():
        target = docs_dir / rel
        if not target.exists() or target.read_text() != expected:
            stale.append(rel)
    return sorted(stale)


def write_nav(repo_root: Path) -> list[str]:
    """Write every generated artifact. Returns the ones whose content changed."""
    docs_dir = repo_root / "docs"
    changed = []
    for rel, expected in nav_targets(repo_root).items():
        target = docs_dir / rel
        if not target.exists() or target.read_text() != expected:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(expected)
            changed.append(rel)
    return sorted(changed)


# --- cli -----------------------------------------------------------------------------

#: Casa's verifier also had `--impact`, which answered "which documents claim this changed
#: path?" for a pre-commit script this repository does not port (the coverage ledger covers
#: the same ground here). The flag is GONE rather than tolerated: an unrecognised flag used
#: to be ignored, so `--impact` quietly ran an ordinary verification and printed a green
#: corpus — a caller expecting the impact answer got a pass instead.
KNOWN_FLAGS = {"--report", "--write-nav", "--check-nav"}


def main() -> int:
    args = sys.argv[1:]
    unknown = [a for a in args if a.startswith("-") and a not in KNOWN_FLAGS]
    if unknown:
        print(f"✗ unknown option(s): {', '.join(unknown)}")
        print(f"  known: {', '.join(sorted(KNOWN_FLAGS))}")
        return 2
    positional = [a for a in args if not a.startswith("-")]
    root = Path(positional[0] if positional else ".").resolve()

    if "--report" in args and (root / "docs" / "manifest.yaml").exists():
        docs_dir = root / "docs"
        entries, _ = _load_entries(docs_dir)
        sizes = [
            (entry["doc"], (docs_dir / entry["doc"]).stat().st_size)
            for entry in entries
            if (docs_dir / entry["doc"]).is_file()
        ]
        for doc, size in sorted(sizes, key=lambda pair: -pair[1]):
            print(f"{size / 1000:7.1f} KB  {doc}")
        near = sum(1 for _, size in sizes if size >= WARN_BYTES)
        total = sum(size for _, size in sizes)
        print(f"\n{len(sizes)} files, {total / 1000:.1f} KB total, {near} within 20% of the ceiling")

    if "--write-nav" in args:
        for rel in write_nav(root):
            print(f"✓ regenerated docs/{rel}")
    # Nav staleness is checked UNCONDITIONALLY: the documented keep-me-green invocation is
    # the bare `python3 -m scripts.verify_docs .`, and a local green must mean gate green.
    # `--check-nav` remains accepted for existing callers; after --write-nav the check is
    # trivially fresh.
    stale = stale_nav(root)
    if stale:
        print("✗ generated navigation is stale: " + ", ".join(stale))
        print("  run: python3 -m scripts.verify_docs . --write-nav")
        return 1

    for warning in warnings(root):
        print(f"! {warning}")

    problems = verify(root)
    # The coverage ledger is part of the corpus contract: a surface the code grows that
    # no document claims is the same defect as a document claiming code that is gone.
    ledger_script = Path(__file__).resolve().parent / "coverage_ledger.py"
    if ledger_script.exists() and (root / "docs" / "coverage.yaml").exists():
        result = subprocess.run(
            [sys.executable, str(ledger_script), "check", str(root)],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            problems.extend(
                line.lstrip("✗ ").rstrip()
                for line in result.stdout.splitlines()
                if line.startswith("✗")
            )
    for problem in problems:
        print(f"✗ {problem}")
    if problems:
        print(f"\n{len(problems)} problem(s).")
        return 1
    print("✓ docs corpus verified")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
